name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check .
          ruff format --check .

      # - name: Test with pytest
      #   run: |
      #     pytest

  build-artifact:
    runs-on: windows-latest
    needs: lint-and-test
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path -Path "requirements.txt" -PathType Leaf) {
              pip install -r requirements.txt
          }

      - name: Build with PyInstaller
        run: |
          pyinstaller --name="Quizleter-ci-build" --onefile --windowed --icon=assets/icon.ico app.py
          mkdir -p dist/assets
          Copy-Item -Path "assets/icon.ico" -Destination "dist/assets/icon.ico"

      - name: Create ZIP Archive
        run: |
          Compress-Archive -Path dist/* -DestinationPath Quizleter-ci-build.zip

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Quizleter-ci-build
          path: Quizleter-ci-build.zip
          retention-days: 7
